# Tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = pre-commit,py{310,311,312,313}

[testenv]
usedevelop = True
deps =
    playwright==1.58.0
    patchright==1.58.2
    requests>=2.32.0
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/tests/requirements.txt
extras = ai,shell
commands =
    python -m pytest tests --tb=short -m "not live"

[testenv:pre-commit]
basepython = python3
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
skip_install = true
